name: Publish to Serverless Registry

on:
  release:
    types: [created]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 12

      - name: Install Dependencies
        run: |
          npm install

      - name: Login Registry
        run: |
          npm i -g @serverless-devs/s
          s cli registry login --token ${{ secrets.PUBLISH_TOKEN }}

      - name: Publish Package
        run: |
          s cli registry publish
          s cli registry list
